name: Deploy to GitHub Pages
on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"
      - name: Install package dependencies
        run: npm install
      - name: Build package
        run: npm run build
      - name: Install example dependencies
        working-directory: ./pdf-vue3-example
        run: npm install
      - name: Build example
        working-directory: ./pdf-vue3-example
        run: npm run build
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./pdf-vue3-example/dist
